version: 2

sources:
  - name: raw
    database: SNOWFLAKE_RND
    schema: RAW
    tables:
      - name: src_client
        identifier: SRC_CLIENT
        loaded_at_field: load_ts
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
