name: Deploy to Production

on:
  push:
    branches:
      - prod

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_CLI_FEATURES_ENABLE_DBT: true

      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PAT }}

      SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

      SNOWFLAKE_DATABASE: PROD_DB
      SNOWFLAKE_SCHEMA: PROD_SCHEMA
      
     steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-actions@v3

      - name: Check Snowflake CLI Version
        run: snow --version

      - name: Test Snowflake Connection
        run: snow connection test -x

      - name: Deploy dbt Project
        run: |
          snow dbt deploy dimclient_dbt_project_object \
            --source ./dim_client_dbt/dim_client_dbt \
            --dbt-version 1.10.15 \
            --force -x \
            --database ${{ SNOWFLAKE_DATABASE }} \
            --schema ${{ SNOWFLAKE_SCHEMA }}
        
      - name: List dbt Projects
        run: snow dbt list -x

      - name: Build and Test dbt Project
        run: |
          snow dbt execute -x \
            dimclient_dbt_project_object_prod \
            build \
            --target prod
